[0.009s] Invoking command in '/home/sunny/ros2_ws/build/custom_interfaces': CMAKE_PREFIX_PATH=/opt/ros/humble /usr/bin/cmake /home/sunny/ros2_ws/src/custom_interfaces -DCMAKE_INSTALL_PREFIX=/home/sunny/ros2_ws/install/custom_interfaces
[0.022s] -- Found ament_cmake: 1.3.9 (/opt/ros/humble/share/ament_cmake/cmake)
[0.141s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.142s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.145s] -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.174s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.369s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.369s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[0.369s]   custom_interfaces --arguments-file
[0.369s]   /home/sunny/ros2_ws/build/custom_interfaces/rosidl_adapter__arguments__custom_interfaces.json
[0.369s]   --output-dir
[0.369s]   /home/sunny/ros2_ws/build/custom_interfaces/rosidl_adapter/custom_interfaces
[0.369s]   --output-file
[0.370s]   /home/sunny/ros2_ws/build/custom_interfaces/rosidl_adapter/custom_interfaces.idls)
[0.370s]   returned error code 1:
[0.370s] 
[0.370s]   Traceback (most recent call last):
[0.370s] 
[0.370s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.370s]       return _run_code(code, main_globals, None,
[0.370s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.370s]       exec(code, run_globals)
[0.370s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.370s]       sys.exit(main())
[0.370s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.370s]       abs_idl_file = convert_to_idl(
[0.370s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[0.370s]       return convert_msg_to_idl(
[0.370s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[0.370s]       msg = parse_message_string(package_name, input_file.stem, content)
[0.370s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 544, in parse_message_string
[0.371s]       msg = MessageSpecification(pkg_name, msg_name, fields, constants)
[0.371s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 388, in __init__
[0.371s]       self.base_type = BaseType(
[0.371s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[0.371s]       raise InvalidResourceName(
[0.371s] 
[0.371s]   rosidl_adapter.parser.InvalidResourceName: 'utm' is an invalid message
[0.371s]   name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[0.371s] 
[0.371s] Call Stack (most recent call first):
[0.371s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.371s]   CMakeLists.txt:12 (rosidl_generate_interfaces)
[0.371s] 
[0.371s] [0m
[0.371s] -- Configuring incomplete, errors occurred!
[0.371s] See also "/home/sunny/ros2_ws/build/custom_interfaces/CMakeFiles/CMakeOutput.log".
[0.377s] Invoked command in '/home/sunny/ros2_ws/build/custom_interfaces' returned '1': CMAKE_PREFIX_PATH=/opt/ros/humble /usr/bin/cmake /home/sunny/ros2_ws/src/custom_interfaces -DCMAKE_INSTALL_PREFIX=/home/sunny/ros2_ws/install/custom_interfaces
